# Generated by Django 4.1.3 on 2023-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_alter_db_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
